# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs|.git|.tox'
default_stages: [ pre-commit ]

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v5.0.0
        hooks:
            -   id: check-yaml
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-symlinks
            -   id: trailing-whitespace
                exclude_types: [ svg ]
            -   id: end-of-file-fixer
                exclude_types: [ svg ]
            -   id: check-yaml
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.6.9
        hooks:
            -   id: ruff
                args: [ --fix ]
            -   id: ruff-format

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v1.11.2'
        hooks:
            -   id: mypy
                additional_dependencies:
                    - pytest-asyncio
                    - redis
                    - types-redis
                    - itsdangerous
                    - fastapi
