# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs|.git|.tox'
default_stages: [ commit ]

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            -   id: check-yaml
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-symlinks
            -   id: trailing-whitespace
                exclude_types: [ svg ]
            -   id: end-of-file-fixer
                exclude_types: [ svg ]
            -   id: check-yaml

    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
            -   id: isort

    -   repo: https://github.com/psf/black.git
        rev: 22.10.0
        hooks:
            -   id: black
                args: [ --config=pyproject.toml ]

    -   repo: https://github.com/pycqa/flake8
        rev: 5.0.4
        hooks:
            -   id: flake8

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v0.990'
        hooks:
            -   id: mypy
                additional_dependencies:
                    - pytest-asyncio
                    - redis
                    - types-redis
                    - itsdangerous
                    - fastapi

    -   repo: https://github.com/myint/docformatter.git
        rev: v1.5.0
        hooks:
            -   id: docformatter
                args: [ '--in-place', '--wrap-summaries=120', '--wrap-descriptions=120', '--pre-summary-newline' ]
