name: Upload Python Package

on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write

        steps:
            -   uses: actions/checkout@v4
            -   uses: astral-sh/setup-uv@v5
            -   name: Build
                run: uv build
            -   name: Publish
                run: uv publish
