name: QA

on:
    push:
    pull_request:

jobs:
    pre_commit:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: astral-sh/setup-uv@v5
                with:
                    python-version: '3.13'
            -   name: Run pre-commit
                run: uvx pre-commit run --all-files

    unit_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.15' ]
        services:
            redis:
                image: redis:6
                ports:
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            -   uses: actions/checkout@v6

            -   uses: astral-sh/setup-uv@v5
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: uv sync --group dev
                env:
                    PYO3_USE_ABI3_FORWARD_COMPATIBILITY: "1"

            -   name: Test with pytest
                run: uv run pytest --no-cov-on-fail --cov starsessions/ --cov tests/
